### ISSUE TITLE
DO NOT USE MY REPO IN PRODUCTION

### ISSUE THREAD

**Issue by Mister-Hope** [Xilin05/shining-blog-site#1]
# DO NOT USE MY REPO IN PRODUCTION

Ref:

- https://github.com/vuepress-theme-hope/giscus-discussions/discussions/646
- https://github.com/vuepress-theme-hope/giscus-discussions?tab=readme-ov-file

**Comment by Xilin05** [comment]
I am very sorry for my carelessneI am very sorry for my carelessness. My Giscus key has been changed, but I cannot find the button to delete the commentss. My Giscus key has been changed, but I cannot find the button to delete the comment

**Comment by Mister-Hope** [comment]
stop using my repo should be fine, otherwise I will be notified about your site reactions. this is the only reason I am being mad at, as I have to subscribe the repo because people do add questions in demo repo sometimes
